name: Branch Police

on:
  create:

jobs:
    branch_police:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Check that branch has an allowed name.
          run: |
            branch_name=$(jq -r '.ref' "$GITHUB_EVENT_PATH")
            if [ "$(echo "$branch_name" | grep -E '^(feature/|bugfix/|invalidfix/)')" ]; then
                echo ""
                echo "The branch name is: $branch_name"
                echo ""
                echo "The branch name does not match the regex: '^(feature/|bugfix/|invalidfix/)'."
                echo ""
                echo "Branch name does not match required format. Failing the workflow."
                echo ""
                exit 1
            else
                echo ""
                echo "Branch name matches the required format."
                echo ""
            fi

        - name: Check that branch does not contain _ characters.
          run: |
            branch_name=$(jq -r '.ref' "$GITHUB_EVENT_PATH")
            if [ "$(echo "$branch_name" | grep -E '_')" ]; then
                echo ""
                echo "The branch name is: $branch_name"
                echo ""
                echo "The branch name contains an underscore character."
                echo ""
                echo "Branch name contains an underscore character. Failing the workflow."
                echo ""
                exit 1
            else
                echo ""
                echo "Branch name does not contain an underscore character."
                echo ""
            fi