name: "Generate and Upload Documentation to Wiki"

on:
  pull_request: main # Temp
  schedule:
    - cron: "0 8 * * 1"  # Runs at 08:00 UTC every Monday
  workflow_dispatch:  # Allows us to trigger workflow manually

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Build Project
        run: make

      - name: Generate Documentation
        run: make docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: build/docs/html  # Path to the generated docs
          clean: true